version: '3.7'

services:
  persistencia:
    image: postgres
    container_name: persistencia
    environment:
      - POSTGRES_DB=persistencia
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - 5432:5432

  backend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8505:8505
    depends_on:
      - persistencia
    environment:
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=user123
      - DB_NAME=persistencia
      - JWT_SECRET_KEY=secretsecretsecretsecretsecretsecretsecretsecretsecretsecret
    restart: always

  frontend:
    build:
      context: ./proyectodiplomadofrontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

